/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedCoachIndexRouteImport } from './routes/_authenticated/coach.index'
import { Route as AuthenticatedCoachSubscriptionRouteImport } from './routes/_authenticated/coach.subscription'
import { Route as AuthenticatedCoachSettingsRouteImport } from './routes/_authenticated/coach.settings'
import { Route as AuthenticatedCoachSessionsRouteImport } from './routes/_authenticated/coach.sessions'
import { Route as AuthenticatedCoachNotificationsRouteImport } from './routes/_authenticated/coach.notifications'
import { Route as AuthenticatedCoachInvitesRouteImport } from './routes/_authenticated/coach.invites'
import { Route as AuthenticatedCoachInjuriesRouteImport } from './routes/_authenticated/coach.injuries'
import { Route as AuthenticatedCoachFollowUpsRouteImport } from './routes/_authenticated/coach.follow-ups'
import { Route as AuthenticatedCoachAthletesRouteImport } from './routes/_authenticated/coach.athletes'
import { Route as AuthenticatedCoachAnalyticsRouteImport } from './routes/_authenticated/coach.analytics'
import { Route as AuthenticatedCoachAthletesAthleteIdRouteImport } from './routes/_authenticated/coach.athletes.$athleteId'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachIndexRoute = AuthenticatedCoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCoachRoute,
} as any)
const AuthenticatedCoachSubscriptionRoute =
  AuthenticatedCoachSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachSettingsRoute =
  AuthenticatedCoachSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachSessionsRoute =
  AuthenticatedCoachSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachNotificationsRoute =
  AuthenticatedCoachNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachInvitesRoute =
  AuthenticatedCoachInvitesRouteImport.update({
    id: '/invites',
    path: '/invites',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachInjuriesRoute =
  AuthenticatedCoachInjuriesRouteImport.update({
    id: '/injuries',
    path: '/injuries',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachFollowUpsRoute =
  AuthenticatedCoachFollowUpsRouteImport.update({
    id: '/follow-ups',
    path: '/follow-ups',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachAthletesRoute =
  AuthenticatedCoachAthletesRouteImport.update({
    id: '/athletes',
    path: '/athletes',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachAnalyticsRoute =
  AuthenticatedCoachAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachAthletesAthleteIdRoute =
  AuthenticatedCoachAthletesAthleteIdRouteImport.update({
    id: '/$athleteId',
    path: '/$athleteId',
    getParentRoute: () => AuthenticatedCoachAthletesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/coach': typeof AuthenticatedCoachRouteWithChildren
  '/coach/analytics': typeof AuthenticatedCoachAnalyticsRoute
  '/coach/athletes': typeof AuthenticatedCoachAthletesRouteWithChildren
  '/coach/follow-ups': typeof AuthenticatedCoachFollowUpsRoute
  '/coach/injuries': typeof AuthenticatedCoachInjuriesRoute
  '/coach/invites': typeof AuthenticatedCoachInvitesRoute
  '/coach/notifications': typeof AuthenticatedCoachNotificationsRoute
  '/coach/sessions': typeof AuthenticatedCoachSessionsRoute
  '/coach/settings': typeof AuthenticatedCoachSettingsRoute
  '/coach/subscription': typeof AuthenticatedCoachSubscriptionRoute
  '/coach/': typeof AuthenticatedCoachIndexRoute
  '/coach/athletes/$athleteId': typeof AuthenticatedCoachAthletesAthleteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/coach/analytics': typeof AuthenticatedCoachAnalyticsRoute
  '/coach/athletes': typeof AuthenticatedCoachAthletesRouteWithChildren
  '/coach/follow-ups': typeof AuthenticatedCoachFollowUpsRoute
  '/coach/injuries': typeof AuthenticatedCoachInjuriesRoute
  '/coach/invites': typeof AuthenticatedCoachInvitesRoute
  '/coach/notifications': typeof AuthenticatedCoachNotificationsRoute
  '/coach/sessions': typeof AuthenticatedCoachSessionsRoute
  '/coach/settings': typeof AuthenticatedCoachSettingsRoute
  '/coach/subscription': typeof AuthenticatedCoachSubscriptionRoute
  '/coach': typeof AuthenticatedCoachIndexRoute
  '/coach/athletes/$athleteId': typeof AuthenticatedCoachAthletesAthleteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRouteWithChildren
  '/_authenticated/coach/analytics': typeof AuthenticatedCoachAnalyticsRoute
  '/_authenticated/coach/athletes': typeof AuthenticatedCoachAthletesRouteWithChildren
  '/_authenticated/coach/follow-ups': typeof AuthenticatedCoachFollowUpsRoute
  '/_authenticated/coach/injuries': typeof AuthenticatedCoachInjuriesRoute
  '/_authenticated/coach/invites': typeof AuthenticatedCoachInvitesRoute
  '/_authenticated/coach/notifications': typeof AuthenticatedCoachNotificationsRoute
  '/_authenticated/coach/sessions': typeof AuthenticatedCoachSessionsRoute
  '/_authenticated/coach/settings': typeof AuthenticatedCoachSettingsRoute
  '/_authenticated/coach/subscription': typeof AuthenticatedCoachSubscriptionRoute
  '/_authenticated/coach/': typeof AuthenticatedCoachIndexRoute
  '/_authenticated/coach/athletes/$athleteId': typeof AuthenticatedCoachAthletesAthleteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/join'
    | '/coach'
    | '/coach/analytics'
    | '/coach/athletes'
    | '/coach/follow-ups'
    | '/coach/injuries'
    | '/coach/invites'
    | '/coach/notifications'
    | '/coach/sessions'
    | '/coach/settings'
    | '/coach/subscription'
    | '/coach/'
    | '/coach/athletes/$athleteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/join'
    | '/coach/analytics'
    | '/coach/athletes'
    | '/coach/follow-ups'
    | '/coach/injuries'
    | '/coach/invites'
    | '/coach/notifications'
    | '/coach/sessions'
    | '/coach/settings'
    | '/coach/subscription'
    | '/coach'
    | '/coach/athletes/$athleteId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/join'
    | '/_authenticated/coach'
    | '/_authenticated/coach/analytics'
    | '/_authenticated/coach/athletes'
    | '/_authenticated/coach/follow-ups'
    | '/_authenticated/coach/injuries'
    | '/_authenticated/coach/invites'
    | '/_authenticated/coach/notifications'
    | '/_authenticated/coach/sessions'
    | '/_authenticated/coach/settings'
    | '/_authenticated/coach/subscription'
    | '/_authenticated/coach/'
    | '/_authenticated/coach/athletes/$athleteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  JoinRoute: typeof JoinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach/': {
      id: '/_authenticated/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof AuthenticatedCoachIndexRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/subscription': {
      id: '/_authenticated/coach/subscription'
      path: '/subscription'
      fullPath: '/coach/subscription'
      preLoaderRoute: typeof AuthenticatedCoachSubscriptionRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/settings': {
      id: '/_authenticated/coach/settings'
      path: '/settings'
      fullPath: '/coach/settings'
      preLoaderRoute: typeof AuthenticatedCoachSettingsRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/sessions': {
      id: '/_authenticated/coach/sessions'
      path: '/sessions'
      fullPath: '/coach/sessions'
      preLoaderRoute: typeof AuthenticatedCoachSessionsRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/notifications': {
      id: '/_authenticated/coach/notifications'
      path: '/notifications'
      fullPath: '/coach/notifications'
      preLoaderRoute: typeof AuthenticatedCoachNotificationsRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/invites': {
      id: '/_authenticated/coach/invites'
      path: '/invites'
      fullPath: '/coach/invites'
      preLoaderRoute: typeof AuthenticatedCoachInvitesRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/injuries': {
      id: '/_authenticated/coach/injuries'
      path: '/injuries'
      fullPath: '/coach/injuries'
      preLoaderRoute: typeof AuthenticatedCoachInjuriesRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/follow-ups': {
      id: '/_authenticated/coach/follow-ups'
      path: '/follow-ups'
      fullPath: '/coach/follow-ups'
      preLoaderRoute: typeof AuthenticatedCoachFollowUpsRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/athletes': {
      id: '/_authenticated/coach/athletes'
      path: '/athletes'
      fullPath: '/coach/athletes'
      preLoaderRoute: typeof AuthenticatedCoachAthletesRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/analytics': {
      id: '/_authenticated/coach/analytics'
      path: '/analytics'
      fullPath: '/coach/analytics'
      preLoaderRoute: typeof AuthenticatedCoachAnalyticsRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/athletes/$athleteId': {
      id: '/_authenticated/coach/athletes/$athleteId'
      path: '/$athleteId'
      fullPath: '/coach/athletes/$athleteId'
      preLoaderRoute: typeof AuthenticatedCoachAthletesAthleteIdRouteImport
      parentRoute: typeof AuthenticatedCoachAthletesRoute
    }
  }
}

interface AuthenticatedCoachAthletesRouteChildren {
  AuthenticatedCoachAthletesAthleteIdRoute: typeof AuthenticatedCoachAthletesAthleteIdRoute
}

const AuthenticatedCoachAthletesRouteChildren: AuthenticatedCoachAthletesRouteChildren =
  {
    AuthenticatedCoachAthletesAthleteIdRoute:
      AuthenticatedCoachAthletesAthleteIdRoute,
  }

const AuthenticatedCoachAthletesRouteWithChildren =
  AuthenticatedCoachAthletesRoute._addFileChildren(
    AuthenticatedCoachAthletesRouteChildren,
  )

interface AuthenticatedCoachRouteChildren {
  AuthenticatedCoachAnalyticsRoute: typeof AuthenticatedCoachAnalyticsRoute
  AuthenticatedCoachAthletesRoute: typeof AuthenticatedCoachAthletesRouteWithChildren
  AuthenticatedCoachFollowUpsRoute: typeof AuthenticatedCoachFollowUpsRoute
  AuthenticatedCoachInjuriesRoute: typeof AuthenticatedCoachInjuriesRoute
  AuthenticatedCoachInvitesRoute: typeof AuthenticatedCoachInvitesRoute
  AuthenticatedCoachNotificationsRoute: typeof AuthenticatedCoachNotificationsRoute
  AuthenticatedCoachSessionsRoute: typeof AuthenticatedCoachSessionsRoute
  AuthenticatedCoachSettingsRoute: typeof AuthenticatedCoachSettingsRoute
  AuthenticatedCoachSubscriptionRoute: typeof AuthenticatedCoachSubscriptionRoute
  AuthenticatedCoachIndexRoute: typeof AuthenticatedCoachIndexRoute
}

const AuthenticatedCoachRouteChildren: AuthenticatedCoachRouteChildren = {
  AuthenticatedCoachAnalyticsRoute: AuthenticatedCoachAnalyticsRoute,
  AuthenticatedCoachAthletesRoute: AuthenticatedCoachAthletesRouteWithChildren,
  AuthenticatedCoachFollowUpsRoute: AuthenticatedCoachFollowUpsRoute,
  AuthenticatedCoachInjuriesRoute: AuthenticatedCoachInjuriesRoute,
  AuthenticatedCoachInvitesRoute: AuthenticatedCoachInvitesRoute,
  AuthenticatedCoachNotificationsRoute: AuthenticatedCoachNotificationsRoute,
  AuthenticatedCoachSessionsRoute: AuthenticatedCoachSessionsRoute,
  AuthenticatedCoachSettingsRoute: AuthenticatedCoachSettingsRoute,
  AuthenticatedCoachSubscriptionRoute: AuthenticatedCoachSubscriptionRoute,
  AuthenticatedCoachIndexRoute: AuthenticatedCoachIndexRoute,
}

const AuthenticatedCoachRouteWithChildren =
  AuthenticatedCoachRoute._addFileChildren(AuthenticatedCoachRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCoachRoute: AuthenticatedCoachRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  JoinRoute: JoinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
